### ISSUE TITLE
Testing 27-06-2015

### ISSUE THREAD

**Issue by ovancop** [biodiversity-checklist/floraINA-peerkalbar#1]
- [x] Forgot password belum jalan
- [x] Gagal buat akun sftp ketika register
- [x] Halaman validate email untuk register salah
- [x] Di halaman user->setting nama kelihatannya dimbil dari username, gk ada field untuk username (ditampilin aja tapi di disable)
- [x] Link one by one blank page
- [x] Gambar yang di detail taxon gk bisa di preview ya
- [x] Individu detail blank page

Temuannya baru itu aja :D tarik @kartikads @widiw

**Comment by ovancop** [comment]
no 2 done

**Comment by widiw** [comment]
No. 5
Setting rootpath sama upload_path nya salah.

Sebelumnya:
$CONFIG['default']['upload_path'] = $_SERVER['DOCUMENT_ROOT'].'/peerkalbar.flora-indonesia.id/tmp/';

Harusnya:
$CONFIG['default']['upload_path'] = $_SERVER['DOCUMENT_ROOT'].'/tmp/';

tanpa 'peerkalbar.flora-indonesia.id'

Barusan gw ganti di config nya.

**Comment by widiw** [comment]
- [ ] Forgot password belum jalan
- [ ] Gagal buat akun sftp ketika register
- [ ] Halaman validate email untuk register salah
- [ ] Di halaman user->setting nama kelihatannya dimbil dari username, gk ada field untuk username (ditampilin aja tapi di disable)
- [x] Link one by one blank page
- [ ] Gambar yang di detail taxon gk bisa di preview ya
- [ ] Individu detail blank page

**Comment by ovancop** [comment]
@widiw itu inputan name di halaman user/setting harus unik ya? kalo namanya sama gimana yak hihi

**Comment by widiw** [comment]
iya kak, di database unik soalnya. Kalo namanya sama mungkin suruh ganti wkwkwk

**Comment by ovancop** [comment]
kita maksa user buat ganti nama berarti hahaha

**Comment by widiw** [comment]
ntar omongin aja ama Cam, db nya dia kan tuh.
Validate <b>Depends</b> di setting user ga berfungsi ya?

**Comment by ovancop** [comment]
Oke santai lah nanti w yg ganti hihi
justru validate Dependsnya jalan makanya setiap w simpan perubahan di kasih warning " Nama sudah terdaftar" padahal w gk ubah name
